const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2348106149503";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_21_58_08_30_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICA0OSxcbiAgICAgICAgMjMsXG4gICAgICAgIDMxLFxuICAgICAgICAxOTksXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMzAsXG4gICAgICAgIDI5LFxuICAgICAgICAxODMsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMzQsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTQzLFxuICAgICAgICA0NCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxOTQsXG4gICAgICAgIDE1MixcbiAgICAgICAgODEsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMzEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMzEsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjAzLFxuICAgICAgICAxNjksXG4gICAgICAgIDE1NixcbiAgICAgICAgMjMwLFxuICAgICAgICA0OCxcbiAgICAgICAgNzNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMzLFxuICAgICAgICAxNixcbiAgICAgICAgMTczLFxuICAgICAgICAyNDcsXG4gICAgICAgIDE1LFxuICAgICAgICAyNTAsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDYyLFxuICAgICAgICAyMTEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTksXG4gICAgICAgIDI0NixcbiAgICAgICAgMjIwLFxuICAgICAgICA0OCxcbiAgICAgICAgMixcbiAgICAgICAgMzMsXG4gICAgICAgIDEzNSxcbiAgICAgICAgNjYsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjUxLFxuICAgICAgICA3OCxcbiAgICAgICAgMTMzLFxuICAgICAgICAyNDMsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTA0LFxuICAgICAgICAzNixcbiAgICAgICAgMTQ3LFxuICAgICAgICA3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNCxcbiAgICAgICAgMyxcbiAgICAgICAgMTU5LFxuICAgICAgICA0MSxcbiAgICAgICAgMjQ3LFxuICAgICAgICA5NSxcbiAgICAgICAgMjA3LFxuICAgICAgICAxMTcsXG4gICAgICAgIDEwNixcbiAgICAgICAgOTYsXG4gICAgICAgIDI1LFxuICAgICAgICA1NyxcbiAgICAgICAgOTksXG4gICAgICAgIDEzMixcbiAgICAgICAgMTk0LFxuICAgICAgICAyMzIsXG4gICAgICAgIDkyLFxuICAgICAgICAxNTAsXG4gICAgICAgIDE2LFxuICAgICAgICA1NCxcbiAgICAgICAgMTI0LFxuICAgICAgICA3NixcbiAgICAgICAgMjI1LFxuICAgICAgICAxLFxuICAgICAgICA4OCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMTMsXG4gICAgICAgIDI2LFxuICAgICAgICA2MCxcbiAgICAgICAgODMsXG4gICAgICAgIDg1LFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDMzLFxuICAgICAgICA0NSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDQ0LFxuICAgICAgICA0LFxuICAgICAgICAxNjgsXG4gICAgICAgIDE1NixcbiAgICAgICAgMzcsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNDMsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTgzLFxuICAgICAgICA4LFxuICAgICAgICAxMTAsXG4gICAgICAgIDUwLFxuICAgICAgICA5OSxcbiAgICAgICAgNTYsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTYyLFxuICAgICAgICAyNDAsXG4gICAgICAgIDEwNyxcbiAgICAgICAgNzcsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMDEsXG4gICAgICAgIDE5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDAsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTk0LFxuICAgICAgICAyMDYsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgOTMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjM4LFxuICAgICAgICA1NixcbiAgICAgICAgMjIxLFxuICAgICAgICAyMTYsXG4gICAgICAgIDI1MSxcbiAgICAgICAgNzEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTc0LFxuICAgICAgICA4NSxcbiAgICAgICAgNzQsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMzQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTExLFxuICAgICAgICAyMzQsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTIyLFxuICAgICAgICA3NFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjIsXG4gICAgICAgIDcxLFxuICAgICAgICAxNjcsXG4gICAgICAgIDgxLFxuICAgICAgICAxNDEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMjE0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTE2LFxuICAgICAgICA2MCxcbiAgICAgICAgMjQxLFxuICAgICAgICAzNyxcbiAgICAgICAgNzksXG4gICAgICAgIDEyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTA2LFxuICAgICAgICAyOCxcbiAgICAgICAgMTYwLFxuICAgICAgICA2MCxcbiAgICAgICAgMjMxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDksXG4gICAgICAgIDMyLFxuICAgICAgICAxODIsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTc4LFxuICAgICAgICAyMDgsXG4gICAgICAgIDMzLFxuICAgICAgICA2LFxuICAgICAgICAyNDgsXG4gICAgICAgIDI4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMzcsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDExN1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMCxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA1MFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgMTY2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDI1MixcbiAgICAgICAgODAsXG4gICAgICAgIDQ0LFxuICAgICAgICAxNjYsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTIsXG4gICAgICAgIDcsXG4gICAgICAgIDQxLFxuICAgICAgICAxMDMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNTYsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTIsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAzNyxcbiAgICAgICAgMTIyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDI2LFxuICAgICAgICAyNDYsXG4gICAgICAgIDU2LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTgxLFxuICAgICAgICA5NyxcbiAgICAgICAgMjE5LFxuICAgICAgICAyMjcsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTQzLFxuICAgICAgICAxMDksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTg4LFxuICAgICAgICAxODYsXG4gICAgICAgIDM3LFxuICAgICAgICA2MSxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDU4LFxuICAgICAgICA3LFxuICAgICAgICA4OSxcbiAgICAgICAgMTE3LFxuICAgICAgICA0MyxcbiAgICAgICAgMTg0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDkyLFxuICAgICAgICAxMCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE0LFxuICAgICAgICA0MyxcbiAgICAgICAgMjQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgODQsXG4gICAgICAgIDY1LFxuICAgICAgICAxNDUsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMyxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMTAsXG4gICAgICAgIDg4LFxuICAgICAgICAxNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjQsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiUzlHRXBua3lwYUY2emZLNTVhdGFDbXkyNDdUcVJYb29oa3pGV3BwYUtBOD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiY1M4ck5jQmpTYm1TNExSbFJhdnhzZ1wiLFxuICBcInBob25lSWRcIjogXCJjZWU1MzYwOC0yNzczLTRmMzEtOWUxYi1jZGRhZWYxZDkxM2JcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjUzLFxuICAgICAgNCxcbiAgICAgIDcwLFxuICAgICAgMTczLFxuICAgICAgMTY4LFxuICAgICAgNzYsXG4gICAgICAxMjcsXG4gICAgICA2OSxcbiAgICAgIDU4LFxuICAgICAgMjI0LFxuICAgICAgMzEsXG4gICAgICAxNTgsXG4gICAgICAxNDAsXG4gICAgICAxNzEsXG4gICAgICAyMzQsXG4gICAgICA0LFxuICAgICAgMTksXG4gICAgICAxMTEsXG4gICAgICAyMDgsXG4gICAgICAxMTdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgOTgsXG4gICAgICAxNzUsXG4gICAgICAxNjIsXG4gICAgICAyMDEsXG4gICAgICA1OCxcbiAgICAgIDEwNyxcbiAgICAgIDEyNCxcbiAgICAgIDIyMSxcbiAgICAgIDUxLFxuICAgICAgMjIsXG4gICAgICAxOTgsXG4gICAgICAxMjksXG4gICAgICAyNDUsXG4gICAgICA3NCxcbiAgICAgIDIwMixcbiAgICAgIDg5LFxuICAgICAgODksXG4gICAgICAyNDQsXG4gICAgICAzOCxcbiAgICAgIDFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiQkI0OEI2NlNcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgxMDYxNDk1MDM6MTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJmaW5lc3PCo1wiLFxuICAgIFwibGlkXCI6IFwiMTYxMzk2MzQ4MjE1NDQ2OjE2QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0kzdnY2a0dFT21BeWJZR0dBVWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwidEFZK21RdGtNUkk3UzNPOUE0N3FDQk1pdnRmWFh6aWVuS2tjZk1INXRERT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCIvQVgzN3BoaWdRaVUrTFBZY0xFYmw2RVZ6a25CODc3bmdvR0xoWG44NWFxQ095bjRFT05BVStEenZRcFZjMWtxSEQvcC9OQ2pLSVlrQkVPYnZTcHhBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCIrSElrTVVMa0JEcG9nN3RKc2FwYUxGdXE3dmZyZDJrNTF1TVZqTGpqaW5HRHErZDBvMWxFbEhwSDlWS0pIL0s4UEYxTVBxRmxqdFJxVUJNQlo3bFdBQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MTA2MTQ5NTAzOjE2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDYsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICA0OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI1MDU1MDg1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSUE0XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJQTQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ3UTcxelhjRnQwN0ZHMDRMT3B4ZGxiTmhxSUV6bTJCcE5Qc2ZSdFVXNWt3PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE2OTc2NDIzODEsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
